-- Script inicial do banco (MS SQL)
CREATE TABLE Users (
  Id INT IDENTITY PRIMARY KEY,
  Name NVARCHAR(150) NOT NULL,
  Email NVARCHAR(255) UNIQUE NOT NULL,
  Role NVARCHAR(50) NOT NULL,
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Tickets (
  Id INT IDENTITY PRIMARY KEY,
  TicketNumber NVARCHAR(50) NOT NULL UNIQUE,
  Title NVARCHAR(250),
  Description NVARCHAR(MAX),
  Status NVARCHAR(50) DEFAULT 'Open',
  Priority NVARCHAR(20),
  Category NVARCHAR(100),
  CreatedBy INT FOREIGN KEY REFERENCES Users(Id),
  AssignedTo INT NULL FOREIGN KEY REFERENCES Users(Id),
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2
);

CREATE TABLE TicketMessages (
  Id INT IDENTITY PRIMARY KEY,
  TicketId INT FOREIGN KEY REFERENCES Tickets(Id),
  SenderId INT NULL FOREIGN KEY REFERENCES Users(Id),
  Body NVARCHAR(MAX),
  IsInternal BIT DEFAULT 0,
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE TicketAIAnalysis (
  Id INT IDENTITY PRIMARY KEY,
  TicketId INT FOREIGN KEY REFERENCES Tickets(Id),
  Category NVARCHAR(100),
  Priority NVARCHAR(20),
  Summary NVARCHAR(MAX),
  SuggestedResponse NVARCHAR(MAX),
  Confidence FLOAT,
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Feedbacks (
  Id INT IDENTITY PRIMARY KEY,
  TicketId INT NULL FOREIGN KEY REFERENCES Tickets(Id),
  UserId INT NULL FOREIGN KEY REFERENCES Users(Id),
  Rating INT NOT NULL,
  Comment NVARCHAR(MAX),
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE SelfServiceSessions (
  Id INT IDENTITY PRIMARY KEY,
  UserId INT NULL FOREIGN KEY REFERENCES Users(Id),
  Question NVARCHAR(MAX) NOT NULL,
  AiResponse NVARCHAR(MAX),
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
  Resolved BIT DEFAULT 0,
  TicketId INT NULL FOREIGN KEY REFERENCES Tickets(Id)
);
